project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: "Home"
  sidebar:
    style: "docked"
    pinned: false
    contents: auto
  page-navigation: true
  back-to-top-navigation: true

theme: 
  light: cosmo
  dark: darkly

engine: knitr

toc: true
number-sections: false

fig-dpi: 300
bibliography: bibliography.bib
link-citations: true

code-fold: true
code-overflow: wrap

callout-appearance: minimal

format:
  html:
    useMath: true
    # Useful only for offline usage
    # html-math-method: katex
    # url: "{{ env.QUARTO_KATEX_PATH }}"
  pdf:
    documentclass: article
    include-in-header:
     - text: |
         \usepackage{cancel}
         \usepackage{mathtools}
         \usepackage{bm}

execute:
  freeze: true
  cache: true
